name: text_sending

on:
  schedule:
    - cron: 0 7,13,19,1 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Send Text 
        env:
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
          PHONE_NUMBER2: ${{ secrets.PHONE_NUMBER2 }}
        run: |
            python reminder.py
